baseURL: http://example.org/
languageCode: en-gb
title: My New Hugo Site
theme: mktest

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  phase: alpha
  logo: text
  logotext: TST
  product: Test Site