baseURL: https://mattkerlogue.github.io/hugo-test/
languageCode: en-gb
title: My New Hugo Site
theme: mktest
publishDir: docs
canonifyurls: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  phase: alpha
  feedbackurl: https://github.com/mattkerlogue/hugo-test/issues/
  logo: text
  logotext: TST
  product: Test Site
  govuk: false