name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build site
    runs-on: macos-latest

    steps:
      - name: setup
        run: brew install hugo
        env: 
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: checkout
        uses: actions/checkout@v2

      - name: hugobuild
        run: hugo

      - name: commit
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add docs/*
          git commit -am "Auto build $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
      